language: python

matrix:
  fast_finish: true
  include:
  - env: TOX_ENV=py33-django-18
    python: 3.3
  - env: TOX_ENV=py34-django-18
    python: 3.4
  - env: TOX_ENV=py35-django-18
    python: 3.5
  - env: TOX_ENV=py36-django-18
    python: 3.6
  - env: TOX_ENV=py34-django-19
    python: 3.4
  - env: TOX_ENV=py35-django-19
    python: 3.5
  - env: TOX_ENV=py36-django-19
    python: 3.6
  - env: TOX_ENV=py34-django-110
    python: 3.4
  - env: TOX_ENV=py35-django-110
    python: 3.5
  - env: TOX_ENV=py36-django-110
    python: 3.6
  - env: TOX_ENV=py34-django-111
    python: 3.4
  - env: TOX_ENV=py35-django-111
    python: 3.5
  - env: TOX_ENV=py36-django-111
    python: 3.6

install: pip install -r requirements_test.txt

script: tox -e $TOX_ENV

deploy:
  provider: pypi
  user: ar7n
  password:
    secure: PWZAV8q1ob1BiJh2BurBgTuu0dCJ5OqH8ghbLtE8QThKfbhrdEYxqRzcj+CnmoRLP6pGtTuTnDth3pXQtk7Mpm6A7fpQ78u04dexApaLBDsX4pXji5FzaHwTWU1SGVv8v0kli7wZwmgDPCc+FVHrUW4/SUS9zTF+ZJGxXAYitLLstMJ++xNrF5XOb5xrjlfvvpfApTxmW8byFkeNgs62rZhxs0vaSCExMwqQlk1XrbocgzGfg95i2q6IPSW6zO1H9NMecNBWA2ImpKfeFfNG8Aq1WwsYZ/0jcAZ2kzfRkUk5OzIKqXZ1hDHFp/vOGJQQ6sK/6dqroENzdCFhclCc4Yi8O8iV89UCGzSRryf18e83pttSZXoQndYaNS/xgxhazz0HcQvj4MndFrU1ounP53t5fUcu/JNL7zBdMgkiFyBDEJ747DggxVUvH+fP04lupyO3cA+1gDMyflVzghWPKHKfxgAlN+YI+nUWmk4ZxkYalo4PEKvVqalL3211SF4J9UlXKAkEBmPNav5mUA0Pnef1LXVYlwI/Eso0jK6FnpT/zfHrEL4vsYV81rwtetMTBdKnreTUfTOcyyaLvFx+QTlGcyvRdYTVz0JfuGbhLzOCokkhnOaEWkt+sqoqwzRBp/oDb1nu/+Zpm+uWAHaLedkz91wbw/3AaycIJPvE2AY=
  on:
    tags: true

after_success:
- codecov -e TOX_ENV
